apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: required-annotations
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://constrainttemplates/required-annotations.yaml
    options: {}
    type: Yaml

