apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Seccomp
metadata:
  name: seccomp
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedProfiles:
    - runtime/default
    - docker/default
