apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCFXzaThqJOt88mxY4P7WbpNgwmvwbkmOmbfxPPt0OoWLghwxbWFYDWXqwEgJG83rNUhHk3GSsMcaH2UlJC4mEUZpeTK/xeb6Y/93zfPxty/xSKK0XThBM2GDoTCyGcrigdW5cETcmumKNWmMl8Dg8smySx/THD8lp3w/w2bHuYYRwpeJDNzZPA2Xiavg9dQwVi8hfCk6Oti0RitxZkRX8Hi5hmZ5f+MUpDDlJidQZ7XoQL2ImxvEQr+m3oFz7s20q1J47OWD664lY3lKIlYfn4Lv1iFuBp/7A6XHh4wnwEYuy+HEEiJIFom4sUZHLn5+Q5uzmTPw5eZ+QhShTXz++ILeCsjozz9Ot4OI0Ber1f9gTjT+XfGqMiEImYY4N59VG3UKsLTTlLlapBHcmsXygKmHOBrOEck4I=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

