apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAFCFaZcHQq6zXX80gxLxxW6e/RMSHF4kuMhHpvQCt+eEf9mfw7UCEtQN2QVnPVHhEBsBAcW9QUmy5Bx1EChv5SRrUimDBNi0XX6aYS6dRB87b8v3s4iqJPwXMKfIqkm1iJk4A4T2Sgwl9e5gl3KHnplRVeYPEP2hqEQWn8i7BmbaSqPk8hr/P2QHRWTZ6YzJOlHP9JV7KFVIgkhGxP7y5tvLqHZNK2yRLzU+aWHD1Qn77y5gBJM7lvHY0cgaITW33i+PqyCoW9+y9YVYIQBKGl+kX4mQRM9mFBB2ouHQp5RdMruhs6pbSFRQkBqpVGd8c/Yi73Zl3Gl8qefPNFmcIEV6PXmGRRByzr9cxjfedGE/oq15clCCbNt/0aw8KtzJhpGhkkq2hwWgZ/mw0GUcfS4JDSV9r7A5A=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

