apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCKQZe51fk5EG+Nvmw7eHLNHFZmZY29aak4NJ9Q11QSOS7Ua6UBU/SuGhDYnikMiqrVMhnQhYi3xC93WPl2hmEAEABcMmp7dWA74IaCNxFJGE7oFXsTTEJmxDdSVLGzDIIj5+prf4iUieBeJTVIpM1H1cKQbrYkFXcFDhrzIrgscg/H/+809GlLTue0UbM48aGxLP6q/hAWxsRg9EEOCY4rWpKURXW3cprqK8dPySUM+V3aukypG4bjpUo14YClA/e211DwR5vf3nBgZEgn6Q8fXmdKQgKU0bXTUHCps/lnFKvw7yT50llbVdql8kKzsK6P3/ttwbv0FciRgFEax2lWKvrOZaYvKbAT60jDO8eLp0KFjYvZNsHzsfsXMzyJm7My6Byq2vtYS7XFPh74e/C919oNdW72qqk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

