apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCY/ou8T6MqRULPrRxiubwVxmmo6DvJcH/bh6ULfTgPoZRTQbFDwTzpjv2gljQr1CUGPfP+bK5Yn/798j6355EkE3QaNwKrilBCaEd70gCb7/SH+E9sPUAPpzNTQFDmGCefFpLJ+ayXgQ+uOrFqVEWmp3NqJINo7U5GkesMKn/1JBfSmWcH4pi6Jx8uBOMQaIYJsEQRvg07fCK7IHwN1eFe7xgy8JEEmCaGTi+piZUVrXLwL8CAVicE7WcYOUG32ZQ8hE68WKHqCPwSuQdKzJUnprjXZG55a5vAY82xybQVQ59aMp+bKNa2VKIlM3zFNm9MNAI5JbRkuxxLT9Zd39WFhph2SGdM81P+fHbFGjuueEl/KUA/Ua568HwRI3RFpO88JKnJ7aNsfVm/kC4vfbciMt8pWFPdzxQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

