apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBjff9j1efsUKg4Nw5dIpMTtqWigu6lUfCQMWd5e6IcMJWcdsmfX/wu3gwwkM3IfIvUFhs3WVPb18qJc2tDbH/C9+tNGYDf6HzR57JClEjlckPi3VbeLhmEAWpMiThXFEd2DY6dI+y4/DKYPXLDvuufBtkN4HoUnJCCxf5l4ob2ZEfdPgct/QjlLGBGBL2gDF+CtCGy+slEi7tkYka2tfSCrl/iHc7+j0/+qhXGIM3ZiRXSgCnpMlNlNGRbyfrM0uXh6IanIdC2e3mfWwC9i0vG0TVcZ5RRPBt3Fla/KWaL+pfP3wKYUTmP2N5ksF4p4rxHg7lPdKZC8ZmXzjyjl4xT2UhmqC7Oe4WuQs+S/drTnTVuaZt/NMEP59tmRV/SV0DM7JYX8s4jkQ7qKwUEWZzu/17mjmXBH0Y=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

