apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCY8/xJREBAQo59yyf6oV0oNx2/Hr022dduIQsbxNvN/K0OIQTLVTTUCX2Kn8sp4QfQAW1eCaOeSIW/S7KQaWosRgiAAQ5i8P+8jnffcr7ZtXwAvNkWSi6ZHbXKBPRhK1Cw3Tu0FZj2n+msEODYdeUq9SEL/0cpb5IvIXNZ+W1GQFG3qi8eNxNkcQs7njjPKxpVtwquAoshhUN/hRvIaIk/yNXrhSa5WDARJa4Y46EjjY+ueyQKPBXJooMw68Nq+gRmuhP7ABHjX5ZaSfq3s7rcB1OTHAzia9KKHOgPnKng10FTQB1qoR8xtryo4XGj3gwTLzsEA8RLQpocbeR53t1SMeEpVV0Fh3wDzPSFhHl/vkVgQ9Wbs5NqqK0FPm27I3LI4rIRYaCRwtpAHqOdavkC9i9LLyS19xg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

