apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBGIhlzsbqQSuJLnBL3KFpCSozandnN4kxqVIl2CzQfMoHhvyHTA2JCSrn/FAy4GHDwZ1zN+4aDIYg9BCLZZb5MfX8MP6K0XtZJ6wSolJD/Advfiq5I3rIGP6eNOUtb516LAqvEH/PIVgmt3gqwmKz5EmJwmyvLxO/Qh2UojZ2MM0q7eQ9HJgVV7s7t71wMTelLN45g2lI7xbifxkXj5IWisjNsQXBL8xfhiEtFkgGfnRXQDFTnpG+t5DOsDcxI0zi2PlbnF/sDviShTtEmLdS84NrFwx2yoIwESU4pZnHlRM/7fUCZMWnsseClMe0GT+HaSVveo0pVuffLVa+4yte0Cl9gZC92X4bpFMmSCF+ESrYs697TUGxEOEjsUpYuBOLpAVgVfu8nTBXwhZo4a1hzz7jGDhWelt0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

