apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQA77WouOwVC/bk/Sn2ZUhs0Iv9nM3NrFPnr8ZJSY8U4i3M+w76qEbSxLGIDDCFaNEH6Baeg+C/wQBPHGjAPB5yHekGnd+wYaa9KNIQcsos2zb6byDFxRKAbi4DXMl5R3dooV5Z3gnCRQmzQ4D/lhejsWPkp2Bok/KSq+rrTRR3oOLTxXo+/Gk6cWThZdPoidfR3ZNp/CaCAFLYN5jZjcxyyI4A1oyvtVgk2YpZztciaQd7YhOSx4GIWt1t97uFngXqITOx1ZH2aW4xmAZtzU7UJl0jl071FejbJYIe1zCZUShKlhQ5SkdMaWTd1bKS7OOpoDytot536/Q/3Pz1AEYrYiV60XqZoImq52d2etSl2BQQzmO6GGxtjKiPc6PHGtmQO1XKJfrJZq7RJPwYHSE235fcXxLgV+Rw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

