apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCJhHE+h4rbgw5LxvknhHOPStZQMD6IOvUf780Z31n4ck5YweFqnXSX4DGoOS6kYdVs/kuk5F+LgVsg5CUxMvCKwbCrSsesiVQpsq9pg6FXUIelHC/tL8pPZ2axoRyllodg8lc+n510C36OemT/ERyWOdj3+M/j2YqSd9XvdKekzvA+Erhw31JyR6jJnDBKzPanK+mbCJ8TAMChzXY37JybUlHaQNMeVq6nuBrAHyoRkiurFnt5SzyHPsyVwrGyWGUF0DTzZf0qq5RubJgPRZBHzusS7ery+jmqYrXuw7bD7t54RzjuuoSMoqr0zBeNqpl4vkXOcoAXB34wD8U7Kp2/ynMYsgeaaR3wKtrZf++9ib+mJJ3IoWmkqmwsXRCYlZTz3rC8++pgQgPsVsRIsRDDqD3GfPB4yY4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

