apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCb9fFMR9G/Ewa9rLWNXlpm0sWw1P8gpWUcNF8/nE3js1DHXPdzdhruxkGPWxfZXs0zUk5NY/NxjmHf4RNCiGScb0mA6U/pj8opo54o63tnOZI+z80vKnfcsG5YUod5/pp+uVkgFQSa2PTdghy9Zv74Bcb//IXGGcsTFAb/fIvysj0JEkCQD9sGDlSVtT8og212/LrVjzrFb4wUdW4JChymzJ9jtxN7Zh5bfCOPiibe0sIYUyufGzrKCP/kSx7gnHsS1/mvvJJOrRDK5bKVDDPXoNnGjZ/Dwum0+8YzQYxwCNz6d1/7eCpSzjNxQXxA2hfg1VqJpZYYZSGrPlS6lDb6SsoxvKm1c6l4rXZ3MpM2Agf9QIu0QyryZRNatyImq7tmvyh9++M/wL0Yi9nq3xYVt0jtzxYIJCo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

