apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBbcYYs/WVETeCyXMq3ojwNGf8PKTj43pktMpVKnDb1DEwJvWgUI5EmAWgk9xAaq/CowEFlN1XxUuVY49fSNgFTs2DeZtuZlbOvcTPbnPEIRTA8OxH72gL0lXbDfod7eDv/HijrntcZNJ3Ws+7sM71Qhl6kkFDtf3YcqC6AFBCuDltoE4DRkOII4eR/oRoPuPhVgHWEWA+tsFhDRF8i9Qq8QXeXKTkhfADXVx//OACHkKOKL5NSTGN01yoe/QC+DtF/sjZ/heFzHBZhsTzEL4OSf4RFyQdwPNIS7tE42PhfZwOjhXh6iYELDWmflLaWbzG7ddxtrYiLRDbrYuHtSXBMcBHCQboI5dU+3qHtPWQrVM/OPrYj/ui2nuCDpGUu7s4UI6a4BiTud5dWzWnsq0u93aDpfTevryQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

