apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQB+dlsBfV7rlu/mKL+jGnpXfU9W5usySfkhVr529CGUM1L2kEr0do56xu8XFK9ORUzidZpHTukTPKOMszoVLpQL3C4KmEXWbdJNJyVWgbEeGvpfdTvMPIaqY4rfk1ghF2mGDhkTeGiXYmOrz+w4hsT3xe/Pj5M2k5NeNkMw3nTyVnOF4zam+AboQuhcg5PumZ7ReKWoP1xc/BY0Pa1J2WwsG73Ny9eNBbqh5Mg9/DSFY/fHIeV/Nnx2qTwKEqZQcof8vPYTCMbAp7DSkQo0eMYUWBdQWlXLT5yq4Ekd9FV7mwVwSDpNPu7ErR1txhpO2l+Dpn7LG6dlrSXZvtKmQPybF2nx8i2+nfim86vIg+ypeG0MkZbuGXCO9Sg9v/u1ewoVEbPxPM45k3m6kW7PE7Y+uKs+YR06eR4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

