apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCEKwLN+4i1IvTgze9+G8XVfrRXUeepZMauZ3gkqXiN+e4/72d+exZgvPn+UvoFJ6RZdQ3sEJRVi8/jm3RvPtxc+P05y88ur9gPdVJJOkGe6p6vJRwD9m6+vq01lG2KkzWr/G/Rvdv+Zo25DWWPO7OJKUq4Nk2AhuoQnYPNXS/r5fJ6ZWj4yZ2ENQ1zhMXMRxf0aBcZDWhYyJRpLOW9eZBWDcQxY2GSrkGS0aueMUNGHL+nR1s0RC4URRd3u+G8V1PnEuu19uc+49OggbFdPzuyVtt3r98fCmut31hEjs7tM/NoYZSjN9EBWB8TOHUY03viLjkWPquWNfJ5t8JVGjoAs4NFT67d1p2IM7ervQV3yh4D8ggJ3QCgU1qfBCZp5+6zpE105xTSY5P0It8+hneKDGOGrbWvLIg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

