apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQANabYmQrQxZYsmrap64uoVuuz5p2siQTBOs5InB7jNaMRXmdFxcrZ/5lnWcM4o1QgY+kXPtmCND3p7Ip6GfDSZJIBkAfL3PPEbBUZWdpJBPAN2LwukYWN901G8vVwneurHNTGcP1uhyVNNHfnKbFP0lF3R6rQKvBtbnOeXGGi0dTRfMCEFJfnaPuB8TznO5pTLJxWKlmRR1U6KDg5E1NWmnNKPyMD5MLh3qVBiFC399ibQBuoyQ5clEHU4qRVUZdqD9j0mLPktJJBpVSOqw4xlvk4nmjMcaHWIJ6YMix51zWRG3uTsjyyBXlaXho8Tjvv1CI+Uz4IMdb7g9PptixutOpW8yAWBFRsHZ2GpDaowNSPGXHBnDZpV6/RWT8s0dFG8VfBXIB/jEZCjuEscVLstFN1PzoSBNs4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

