apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBxRwjs9+w1/ZSLQoAXjnxVJt1C/MuoE4mcDvvS92nDPv4rQmYeHXJaP50DBVZAEkykD1CMCdbnDSP6Gcn/XPUUeBHNeOUZ40/XNkvX86N1cASLHtO4zvZbNf107YDlEZzfiQ1dXlL5e6UGoJOGHgFYKjhL4QLb7AbcEiex5yrS1vmrp1JYBWicCuTRhxnaxOdt3nb8gyyk+EmYzYQATmBy84uJomvKDQwWeMsivRmFo0jSssCUhAiAoud+FL3udS94o36TKUyPLrVKVB/P7YSTRwwkSxvCRv8YuLZPBW8PsEWv1Mx0CCG72Zoz4yo7NCQ8FxPE/jLdntvSWr8t2jzgf0ue20r20DdhKkOUcNgq0OnfyGc6+1vrrlvdg8MDzaMDsh91dAMS2JlIMOz+LrjEYDYaLpuA7wI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

