apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQACc9LOGBJHEtJHaWsSRa7+K6RyocgXHtuSiEGH+dHGRzbF7v1I2zmUNCt1aLWvTiPzQORbpGQsnzMyDJopF5X+H6QyTmH3unMhk+4DZlZRbWsoXidmyCvhTHQZ5G5fnBRdTh6/LBUqLdq56X2V3eRPGBU+0mU3etcl9llvHRs68KVJiy4geC48eo2VfzjvfauRafzEbyr3VAXiCGEml5LWrJvfL/CINYuQiBgO+b9MrO55xwzLORh7sDzBx8bNq9rflQ/wXOZfrsXPJ6SEYJRhIf9VRy3vC5iXtELrJZY53izhfksb9ousDxhfZphTPose5L0ua2KscFsOglCUzAWyw5VTCvd6q/cjB684sCRZ1qLciu0m+Slifwylkx+vBisqFxd0nOyA/z6T7n/gS6Ib2vCEWpYPFAk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

