apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBVc9FcDMyc4kI192E0E+86rKwWMqq8EUUtRz/z8O+ldxF2/txXvBKabrlSPCzcIcSWp8jOHkBdpZjaE+oAFyBm5Ys823RmbOmnqgCk+8iXS1pwVodqPNC20gofbhq+PDPnA+MVDQiwxBAWhXzFjeVMQISp4zQ6xRtwcOH4ZMDdB/xiiiyab0rBkp7zIXcvJLRbHA73/2uKdEuUW6GquoBSl4BEGCwX7qkyNftpuvrwld93PUtRNliJInIrSx0jpKtmN+LfzaCGxB8NP/viLhTCMKrwRyDFu51XYcI2ZMcmDK9Ee3nmxHHF+HNFZLkueL7TPRns722/AunhZeXOJQjmLX3uNmRK2KzyeF4rlXBDl5uu4V5ybg7jlEPj/rNDw59JgX7iN91edjPGibmjVB/Wq/TMkMLqYbM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

