apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBk4QIgCrS3OM45QwNng6Opexy4MTaKiunnmG2wmdZ7vcwu61R07Sz6ErrwCBGJBtf9HjX7qaqCMLs0A3Z9wFlF6Cw2Ket1AxKdUDbedWEv9cCwfze+WwUDbBhMRZNzKUXN1Y7/C5qdfls6lgi9jnHBA74tr+cmkNAVJvoUc7IArGRMjQP1pIIgrdKAU103+jE7SInWgl46Db57Ya1ZW+E8PM4cj813tDHrX67NlJNMRygB7nYDCv09dTo6yFAgNoxKBMo4pdZWsql7f3eceaipp2jMO7LGz/m/aYe3DVMZtnBtJF5gOShR9gByHuynl68LW20yArOkWKu73VDpk0yA3Ht/dMh6y4HmgdCo4wRgwLG1G2vIQ3e1R1V0XANB3uLdBieFO2//6kOH6WGnSuyQ54Xg+pHzTl8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

