apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQChqETSNUjfqqbCxEfNjhtCxSNL59I70dbshR25KRZA75PUPs13tisimANAOU4GzlgUWEGV6L9qs3F70pkonqSZD61hqoLbK5lj0viphBHfHoRLHw6GFGuUkgNZTM7DzC3mhtCQMJHstA4XuZanOvU3rDJ5S4rekfjwatdu16lK7IZGDOybz8aWHXNWMM31IWlTzC73bCpFFSQ6T3oHd7L77yWmEYiaO3L3Puv/SsTGsACjx9EVFhLy7QfZ1N1IzeG/TnDINQ89QAqyDXNPg0Q3bH7oj+6PEUt9eoHx3rO/KV7lHQDdckW6M+Vp7ZT/qRj0ixW9x8qIQ1MHPcPTKMvZkFhxCr9nSCUw9QWEmxfeDlvqLgtghSbRSUrF1SPADv8CLCZ3zgnEGGXz2/5FYpoRHHrZ8/Fsi7o=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

