apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAy0EK4A/iBwpt75rVkkPX3B4Bkwt9JMY+dAOSMIGJkc4anqazsMHU7YeNeQEGcI1IgezYZxja0FIJlGEiAD0HnsPyijs6O2k6oXcBkC6Rch3jqmKaF2FgOZ7Iac1a6/LpTNV2TpQpuuZjp5FZNH6yF6ckywzTk52BwiPVmEYiNZyqSmJ3ZEF+TEmH7PgczWZOh+ko03j4cJ6K8syzz1z+2uJtkSB9WhdVcwkwE3P7FR0Uoqn2jG5XVIrB43NJGDATL8UlmdNHQDcEF2wNcbglttarw2q6auJNcvyNvYd8G68XnpGaNEX+3J+yflz+U68+Pno1p3x+vefRcvEv3eGinAC8ZMBv1yguZeSm+C2MFvv12WKbEGTtRYp+gxTy2fqaeL1Wo1WqPnU6ld8sAVAtoUFlqyu6D+O0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

