apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCIeRhCdQbO6mGPOBppHITt17uXBN5W5p405qynVrB305B2EeOX7ssuTZ45tscYsBWjnCiD+ccXRa366D4biIvD4l6paswgICKsvtEaEdWX0naQ2xAVqokP3ZhyYEszGO1mQNcusY+IBguTnxwlWsdUpu2HhYBVvburhNMO9gLNU6fjPLhVa/q5wKKgqW7XP+ug0UY9E0CEXHtY4AXn6SIbl6h+kv37RshV0hgqOsbzSMJ3Eo4mUOmsyb/xyijDIJnqaVXKdjhsL2AyH38YNm8LiOlZ0FpSxf63p8F73cSwzZ+PoP9+qTFwxhfqSB2dZ7CZaqtN0NQ9Xpgr4hn/LBs4KkKqFfdPwOUNLUVQxiQYBC6lQUoBBV/VM45UsrTrT4zPpQ9ho4JLphWJOezShebc1d+nDhhI9GU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

