apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCKOZGfmF3PpBgFhi56h2CWMDPqeQXyPqJn1zWi1+//KIafTr5WWgOUVsTVQNzfmHdWrXxeDpURNJJAB5jIbLUArlf4kKEiahKOn5daemZK39+g9IvmaWya263HPYDbauLP+rrhs6ODiBiGRsiJPN1bWC4BnSz8mb595sTse45gbehvh+UBPih5EdXZsL9sZYWlPAfDvaG7zJBzZ/cM1fApG1SLEggJJfw89BV5oZMp8gUI7FoQA8tmbN1yFcIFQtwmeI/L/bU8v4RGOkhxCbKvLgai1PZwsD8BgVOoLrpnSHah//KGXW0AT0AeznFwdFS34OmqIQ2Fz6vipVVXFQ4/ILy8CKu9oEP2mLDzUjJQ7c9bcjNuxLu8UTyOHmSiycmy4QVbnAufMN42oBd/s2K9nV+Rm7Netfo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

