apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAHRVw0OSQ3tdD5kAid95+HSnbZZwoK2nglZtAZGXI8sEkR3IdlE3E0v+wcQ23LAXJYv/aWy64gNj6VrUTzYe5nuWttz4dpTS43Al6xFSza8V1STzKRtOnbidzFPKkDnVTz+SzNOZUbM6TQCVbGkPyRxcO+WPEGhZlco9/ZqlwbKexKOeg8yu59GLMH3H9+led9ipy5Gq0yObMDEfpId+QOR5FRrOSaC3fTPGAUSmGtoyculQRAbThguB5KHPRbylD0muezKKvmP+uR//r/1L/FGmTLw8urJJC+LFg1R4n/S/RQsm4OWHPYOcLb+y/4J1uUU9FwXexeUD7rgkNc/RobAUo/o1hgnhTKZu+yuQhYkMwCLeSArEV/RJ4JHR+83kYRAUykaoFPT04lLPxm/c2NnaK875RVtJM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

