apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBdSoFtb35ug+mplAGstb0WJGIfVvvyw20ishDRVfNNs2ndr3SDZaymNtv9Op6wbqnRL0aaMYWfvD3/r35YMH9hAX9Yvd1R251CXlRJh+wT1QM16/6n0hKRP7S3yZkgNFdtcm8YWfTCH6sHfyaKqw6NubGZjjkGB0Cn8OvrkXJFvMBYrSHDkuf9gPHQ/W01SkIewlkyylic3JgzaHW3r2i+x6Jt6RxP0Jcq69iNWBSaFvY5GYWmTHil7jlBhJrCZeXyhLIWV4sqADBKbeJqxHc9jmfutS8bM++2t11C4yFhqFUBpwu91qomOY/wjbam4a0UtMjUVVtXZ2gQi9W1y/f3+3PFdXjyJzJdqMi1ExTnrdJTEcGj6p9kaWusKrmHepxrGVXMoF9vXnhK9A/4qjBr+f6jh9puzU0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

