apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCm5rDeclJmzjiCbjaPNeBb6qJy85ghXZxoGFAFD3uhkjKJFHgh1qjSyLIcTGhEKzjG3k3Os7FVDM/H4zq/N9n0mIFjevFIjAKUgBdEPeYtIZ2rCr5qLMNbfouFzi6Tw5AflAm0kM6lMSFWi7X+H2S1WJdBIsBki3I1lGL6qxnys6+sQdWL0IfjHDDUYG4dPnHCU8B+TmceUXLBSj1j/LkTt/RgoY8H+Ty9gKgraTns5Iqu+4Vl1q12l5VYH44m3jds1ci6Tl+pFiq7NXHcs9RD7sd4FsAfVm+123DS+VZL9VcgQFPRIA9Re+FCNBHBqVgmP4bNd9FgutriiFXNQCcAcbO9FHx7TV9g25qhu0djgL3cSX4+MmkG8JPG1R3W+Ev0EEAs5mna27Vs6/OaaoPoirgfEqwKOMg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

