apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAGdawjM81bRZuOUncfxBRor4EDWPESqp4RIw+8sNNdjvW/kZx50xuIkzuFMjxyT6ZSuLGYk08uwKzmxqrQC2dtn6HDZdRTdLLANfDTBnNXg9nxZMswvYNNSZgZYyr92uAW42oHPT9gaIYYdgLZqTX4dLkm/jt2vllJwkX28U2mPXSPMN6eH91uI0PReM7HGxPMYnJsD+PLVpOUEq60kGdLxcwzP4kTKHYngRCIKhUrfWBVy25oWEVNmusX/72R+jktHiZGB7JRAaD8PQ/1fZGxaZtSSRSakANkBPWVWoyXBWrpwYszFlfsg3zhHEvyg0ts02XfdrSGEzjdc52y7Nx1jvEh2VwW2chVpCvRCxeeYIqTWHVx0KVrFUHjbBXuI4nvZeAcCBOFLbnFBujoH8Sf7RRJIaIaQac=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

