apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAH4RKZZh58oOvOk1SrhB0/bvT57D654o34t14KTMN2eXWFVWWbDaenHFYlQ6uFzmDkLm2JuZK/A2Qye8j9Qa8/WbSo+Y6ZqT3HlrX91OhaHbjx9f94EcxLSbfbRjhlRTWMkZxDjOXhDuJwhRECK7LSSVY09l0lFf++DKQG5KLy6TF6qrbZiDS/NC8QeYrxGFsl8Z4RgfD0HZ7C9iQf8diPAax1N74HROMrE54z75pO4U0O97kOdT/08IZb1OrhtQR+Qd3wgYy3nZpOa/KzUbG/QFfkfJJqs+p2Q7RX77lnczgLR/zITYZO3J3dbiGOceacsVV4fiWpRXryyy70QE7tu0Y7wIU2VMszGcGQ9nOpMJs59ixfkra1khklR8VvMjumSXMT9GWScN8xdXXtQnNNanx9OIGwc5s=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

