apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAhOSHLaobCjQevCOlE5A6yb1hfg7ofR4hdCPbu0kgomFMZi8goA0Uk+iyzGoC0tLcU7F4qQDDHPGLUNrePtDqVoEIRXlxfibNjnlv0qpBbCSw0AREc5Jrsc3uSjhxk0BnCe4yLedwNZyKq2Egbq9g24tDHp3FpEc4TvAggGDlao36U8gpa5wH4C0VBiLrQyn0PjvAtrZ0MB/DoxjB8BcSBc4XvMyC4D92wzMCNVPbCaGl9SMb4rQf1huDuZTzHOpdvhicop/O9uBT4Z2VshUJNB5g6QjPgZ4PJL6hjgDx3dBikQI+/SCEmhaUfwDLFPw19N+04JDO9vnI2x5cPtDMQWLC4eKhSbRpE3hsIOXyBwRu0So3xO502XVXqd1/e1zr/cXGlXEaPSA3qj1hkPBNNORUVSb/bO0c=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

