apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQA6MYADOFTZfABEwHq6BzoYTmtAO+vO5jLi3BYBK2yH4M8CFHyMzJTZamwO/pU+aWj9IBLom/ttSmfjG3YzcyCOLi8WN8cQS6o7tXXrQjnNGUIA/xXP9jJX6Dklp/V7/aU95Ekrwh07p7hkC1teBQB25Pip0Rq3IF86GE6tg1Cg7HmZ1gOE7x1GUwPawXPvBjofkkP8ubPcLgbJk7e2wDoUvUcGczgNOqwy3+FAmV1vOlupFgE/rTGI3GBTY7R6iUbJmsByAAYoNBi64oJGnQB8ew/7Q9h76Y0CtLfnTNjOiHo+2x3qKOdt2QpIYBelA0LgwM52xYY7Pzka+y7VN+SVWYWflzWp/2gHWgpScFAkxlAKRHip0Q1iMyNVxqSQji9uyz1sid8GOS0GsNM965AqpiTn3/NhrwU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opa
      namespace: default

