apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: proc-mount-custom
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://constrainttemplates/proc-mount.yaml
    options: {}
    type: Yaml

