apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: two
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/two/gatekeeper-allowedrepos-policy-constraint.yaml
    options: {}
    type: Yaml
  templateName: two
