apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: two
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/two/gatekeeper-allowedrepos-constraint-template-regex.yaml
    options: {}
    type: Yaml
