apiVersion: opa.k8smgmt.io/v3
kind: OPAPolicy
metadata:
  name: one
  project: defaultproject
spec:
  constraintList:
  - name: one
  - name: host-network-ports
  - name: host-namespace
  - name: seccomp
  - name: host-filesystem
  installationParams:
    auditInterval: 60
    auditMatchKindOnly: true
    constraintViolationsLimit: 20
  sharing:
    enabled: false
  version: v23
