apiVersion: opa.k8smgmt.io/v3
kind: Constraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: one
  project: ankit
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/one/request-limit-ratio-constraint.yaml
    options: {}
    type: Yaml
  templateName: one
