apiVersion: opa.k8smgmt.io/v3
kind: OPAPolicy
metadata:
  name: bp-all
  project: defaultproject
spec:
  constraintList:
  ########PSP-Restricted################## 
  - name: allow-privilege-escalation-container-custom 
  - name: allowed-users-custom                        
  - name: app-armor-custom                            
  - name: flex-volumes-custom                         
  - name: forbidden-sysctls-custom                    
  - name: host-filesystem-custom                      
  - name: host-namespace-custom                       
  - name: host-network-ports-custom                   
  - name: linux-capabilities-custom                   
  - name: privileged-container-custom                 
  - name: proc-mount-custom                           
  - name: read-only-root-filesystem-custom            
  - name: se-linux-custom                             
  - name: seccomp-custom                              
  - name: volume-types-custom
  
  ########BP-REliability##################
  - name: disallowed-tags
  - name: replica-limits
  - name: required-annotations
  - name: required-labels
  - name: required-probes  
  
  ########BP-security##################
  - name: allowed-repos
  - name: block-nodeport-services
  - name: https-only
  - name: image-digests
  
  ########BP-Operational Efficiency##################
  - name: container-limits
  - name: container-resource-ratios   
  
  excludedNamespaces:
  - namespaces:
    - name: namespace-1
    processes:
    - '*'
  installationParams:
    auditFromCache: false
    auditInterval: 60
    auditMatchKindOnly: false
    constraintViolationsLimit: 20
    enableDeleteOperations: false
  sharing:
    enabled: true
    projects:
    - name: defaultproject
  syncObjects:
  - group: extentions
    kind: Pod
    version: v1
  version: v1