apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: image-digests
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://constrainttemplates/image-digests.yaml
    options: {}
    type: Yaml

