apiVersion: opa.k8smgmt.io/v3
kind: Policy
metadata:
  name: one
  project: ankit
spec:
  constraintList:
  - name: one
  - name: host-network-ports
  - name: host-namespace
  - name: seccomp
  installationParams: {}
  sharing:
    enabled: true
    projects:
      - name: defaultproject
  version: v2
