apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: one
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/one/request-limit-ratio-constraint-template.yaml
    options: {}
    type: Yaml
